#!/bin/sh
# Jeffrey Fulmer <jdfulmer@armstrong.com>
# Sat Jan  6 11:36:27 EST 2001
#
# part of siege distribution
# automates the autotools

set -x
aclocal 
autoheader
automake --foreign --copy
autoconf
utils/manifier doc/fido.pod doc/fido.1.in
utils/manifier doc/fido.conf.pod doc/fido.conf.5.in
